// Was generated by @nuxtjs/pwa (nuxt.config.js `manifest`).
export const GET = () => new Response(JSON.stringify({
  name: 'Laravel & VueJs', short_name: 'Laravel & VueJs', description: 'Laravel VueJs', lang: 'en',
  start_url: '/', display: 'standalone', theme_color: '#42b883', background_color: '#35495e',
  icons: [{ src: '/icon.png', sizes: '512x512', type: 'image/png' }],
}), { headers: { 'Content-Type': 'application/manifest+json' } })
