// Same Prism setup as the Nuxt plugin (plugins/prismjs.js), loaded in the browser only.
// Languages load first: the previewers plugin extends the CSS grammar (css-extras) at import time.
import Prism from 'prismjs'
import 'prismjs/components/prism-json'
import 'prismjs/components/prism-css'
import 'prismjs/components/prism-css-extras'
import 'prismjs/components/prism-markup-templating'
import 'prismjs/components/prism-javascript'
import 'prismjs/components/prism-php'
import 'prismjs/components/prism-markup'
import 'prismjs/components/prism-typescript'
import 'prismjs/components/prism-sass'
import 'prismjs/components/prism-scss'
import 'prismjs/components/prism-bash'
import 'prismjs/components/prism-git'
import 'prismjs/components/prism-nginx'
import 'prismjs/components/prism-graphql'
import 'prismjs/components/prism-less'
import 'prismjs/components/prism-sql'
import 'prismjs/components/prism-ruby'
import 'prismjs/components/prism-perl'
import 'prismjs/components/prism-twig'
import 'prismjs/components/prism-docker'
import 'prismjs/plugins/toolbar/prism-toolbar'
import 'prismjs/plugins/command-line/prism-command-line'
import 'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight'
import 'prismjs/plugins/highlight-keywords/prism-highlight-keywords'
import 'prismjs/plugins/line-numbers/prism-line-numbers'
import 'prismjs/plugins/line-highlight/prism-line-highlight'
import 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard'
import 'prismjs/plugins/show-language/prism-show-language'
import 'prismjs/plugins/wpd/prism-wpd'
import 'prismjs/plugins/previewers/prism-previewers'

window.Prism = Prism
export default Prism
